# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pydantic models for Ad Templates (The Schema)."""

import pydantic
from typing import List, Literal, Optional


class CinematographyHints(pydantic.BaseModel):
    """Hints for camera work, lighting, and visual mood."""

    camera_description: str = pydantic.Field(
        default="",
        description="Desired shot type, angle, and movement (e.g., 'dolly zoom', 'handheld tracking shot')",
    )
    lens_specification: str = pydantic.Field(
        default="",
        description="Hints for focal length, depth of field (e.g., '85mm f/1.8 shallow DoF')",
    )
    lighting_description: str = pydantic.Field(
        default="",
        description="Keywords for lighting setup and mood (e.g., 'golden hour backlighting')",
    )
    mood: List[str] = pydantic.Field(
        default_factory=list,
        description="Emotional tone keywords (e.g., ['dramatic', 'urgent'])",
    )
    color_anchors: List[str] = pydantic.Field(
        default_factory=list, description="Key color references for the scene"
    )
    velocity_hint: str = pydantic.Field(
        default="Standard",
        description="Guidance on the speed of motion (e.g. 'Fast', 'Slow', 'Ramp').",
    )


class AudioHints(pydantic.BaseModel):
    """Hints for audio elements."""

    dialogue_hint: str = pydantic.Field(
        default="", description="Guidance for narration or character lines"
    )
    dialogue_tone: str = pydantic.Field(
        default="",
        description="Style of the dialogue delivery (e.g., 'professional narrator', 'excited user')",
    )


class TransitionHints(pydantic.BaseModel):
    """Hints for transitions between scenes."""

    type: str = pydantic.Field(
        default="cut", description="Type of transition (e.g., 'cut', 'fade', 'wipe')"
    )
    duration_seconds: float = pydantic.Field(
        default=0.5, description="Approximate duration of the transition effect"
    )
    description: str = pydantic.Field(
        default="", description="Text description of the transition effect"
    )


class SceneDefinition(pydantic.BaseModel):
    """
    Defines the structure and constraints for a single scene in a template.

    Fields marked as [PREDEFINED] are hardcoded in the template library and enforce consistency.
    Fields generated by the AI (like the final prompt text) are derived from these constraints.
    """

    scene_id: str = pydantic.Field(
        description="[PREDEFINED] Unique identifier for the scene"
    )
    duration_seconds: float = pydantic.Field(
        description="[PREDEFINED] Target duration of this scene"
    )
    purpose: str = pydantic.Field(
        description="[PREDEFINED] The narrative goal of this scene"
    )

    # Structure
    transition_from_previous: TransitionHints = pydantic.Field(
        default_factory=TransitionHints,
        description="[PREDEFINED] Hints for transition from the previous scene",
    )

    # Defaults/Hints
    cinematography_hints: CinematographyHints = pydantic.Field(
        default_factory=CinematographyHints,
        description="[PREDEFINED] Hardcoded visual specifications to ensure cinematic consistency",
    )
    audio_hints: AudioHints = pydantic.Field(
        default_factory=AudioHints,
        description="[PREDEFINED] Guidelines for tone and sound design",
    )

    # Guide for the Agent
    asset_guidance: str = pydantic.Field(
        default="",
        description="[PREDEFINED] Instructions on what kind of user asset fits here (e.g. 'Product Hero Shot')",
    )
    on_screen_text_hint: str = pydantic.Field(
        default="", description="[PREDEFINED] Suggestion for text overlay content"
    )


class AdTemplate(pydantic.BaseModel):
    """Schema for a complete Ad Template."""

    template_name: str = pydantic.Field(
        description="Descriptive name (ID) for the template"
    )
    industry_type: Literal["General Purpose", "Vertical-Specific", "Social Native"]
    vertical_category: str = pydantic.Field(default="")

    target_duration_seconds: float = pydantic.Field(default=30)
    use_voiceover: bool = pydantic.Field(
        default=True,
        description="Whether to generate a narrator voiceover (False for UGC/Selfie style)",
    )
    generate_virtual_creator: bool = pydantic.Field(
        default=False,
        description="Whether to automatically generate a consistent character asset for the campaign.",
    )
    veo_method: Literal["image_to_video", "reference_to_video"] = pydantic.Field(
        default="image_to_video",
        description="The method to use for video generation (standard image-to-video or reference-based).",
    )
    description: str = pydantic.Field(description="Description of best use cases")

    # Global Style Hints
    style_preset_hint: str = pydantic.Field(default="")
    brand_personality: List[str] = pydantic.Field(default_factory=list)
    music_keywords: List[str] = pydantic.Field(default_factory=list)

    # Structure
    scene_structure: List[SceneDefinition] = pydantic.Field(
        description="Ordered sequence of scenes"
    )
